// 부동산 매물 데이터 - 서울 주요 지역
const properties = [
    // 강남구 매물
    {
        id: 1,
        title: "신논현역 초역세권 신축 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 500,
        monthlyRent: 60,
        address: "서울시 강남구 논현동 123-45",
        district: "강남구",
        area: 33,
        rooms: 1,
        bathrooms: 1,
        floor: 8,
        totalFloors: 15,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락"],
        description: "신논현역 도보 2분 거리의 신축 오피스텔입니다. 분리형 원룸으로 공간 활용이 우수하며, 남향으로 채광이 매우 좋습니다.",
        lat: 37.5048,
        lng: 127.0242,
        image: "https://picsum.photos/seed/prop1/400/300",
        agent: {
            name: "김부동산",
            phone: "010-1234-5678",
            company: "강남부동산"
        },
        premium: true,
        views: 1234,
        createdAt: "2025-11-25"
    },
    {
        id: 2,
        title: "강남역 대로변 투룸 오피스텔",
        type: "투룸",
        saleType: "전세",
        price: 35000,
        monthlyRent: 0,
        address: "서울시 강남구 역삼동 789-12",
        district: "강남구",
        area: 45,
        rooms: 2,
        bathrooms: 1,
        floor: 12,
        totalFloors: 20,
        buildYear: 2022,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다", "주차가능"],
        description: "강남역 5분 거리, 분리형 투룸으로 신혼부부에게 최적화된 공간입니다. 관리가 잘 된 깔끔한 매물입니다.",
        lat: 37.4979,
        lng: 127.0276,
        image: "https://picsum.photos/seed/prop2/400/300",
        agent: {
            name: "이공인중개사",
            phone: "010-2345-6789",
            company: "역삼공인중개사"
        },
        premium: true,
        views: 892,
        createdAt: "2025-11-26"
    },
    {
        id: 3,
        title: "압구정 현대아파트 리모델링",
        type: "아파트",
        saleType: "매매",
        price: 180000,
        monthlyRent: 0,
        address: "서울시 강남구 압구정동 456-78",
        district: "강남구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 15,
        totalFloors: 25,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장"],
        description: "압구정 현대아파트 84㎡ 매매입니다. 최근 리모델링으로 새집처럼 깨끗하며, 한강뷰와 학군이 우수합니다.",
        lat: 37.5272,
        lng: 127.0286,
        image: "https://picsum.photos/seed/prop3/400/300",
        agent: {
            name: "박중개사",
            phone: "010-3456-7890",
            company: "압구정부동산"
        },
        premium: true,
        views: 2341,
        createdAt: "2025-11-24"
    },

    // 서초구 매물
    {
        id: 4,
        title: "교대역 풀옵션 원룸",
        type: "원룸",
        saleType: "월세",
        price: 1000,
        monthlyRent: 55,
        address: "서울시 서초구 서초동 234-56",
        district: "서초구",
        area: 26,
        rooms: 1,
        bathrooms: 1,
        floor: 5,
        totalFloors: 8,
        buildYear: 2021,
        options: ["에어컨", "냉장고", "세탁기", "전자레인지", "인덕션", "신발장", "붙박이장"],
        description: "교대역 도보 3분, 풀옵션 원룸입니다. 관리비 저렴하고 치안이 좋은 지역입니다.",
        lat: 37.4936,
        lng: 127.0143,
        image: "https://picsum.photos/seed/prop4/400/300",
        agent: {
            name: "최공인",
            phone: "010-4567-8901",
            company: "교대부동산"
        },
        premium: false,
        views: 567,
        createdAt: "2025-11-27"
    },
    {
        id: 5,
        title: "방배동 래미안 퍼스티지",
        type: "아파트",
        saleType: "전세",
        price: 65000,
        monthlyRent: 0,
        address: "서울시 서초구 방배동 567-89",
        district: "서초구",
        area: 114,
        rooms: 4,
        bathrooms: 2,
        floor: 10,
        totalFloors: 20,
        buildYear: 2019,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨"],
        description: "방배동 최고급 아파트 래미안 퍼스티지입니다. 학군 우수하고 교통 편리한 위치입니다.",
        lat: 37.4812,
        lng: 126.9964,
        image: "https://picsum.photos/seed/prop5/400/300",
        agent: {
            name: "정부동산",
            phone: "010-5678-9012",
            company: "방배부동산"
        },
        premium: true,
        views: 1456,
        createdAt: "2025-11-23"
    },

    // 마포구 매물
    {
        id: 6,
        title: "홍대입구역 신축 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 3000,
        monthlyRent: 70,
        address: "서울시 마포구 서교동 123-45",
        district: "마포구",
        area: 35,
        rooms: 1,
        bathrooms: 1,
        floor: 7,
        totalFloors: 12,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락", "택배보관함"],
        description: "홍대입구역 5분 거리 신축 오피스텔입니다. 주변 상권 발달하고 대중교통 편리합니다.",
        lat: 37.5565,
        lng: 126.9236,
        image: "https://picsum.photos/seed/prop6/400/300",
        agent: {
            name: "강공인중개사",
            phone: "010-6789-0123",
            company: "홍대부동산"
        },
        premium: true,
        views: 1823,
        createdAt: "2025-11-28"
    },
    {
        id: 7,
        title: "합정역 투룸 오피스텔",
        type: "투룸",
        saleType: "월세",
        price: 2000,
        monthlyRent: 80,
        address: "서울시 마포구 합정동 456-78",
        district: "마포구",
        area: 42,
        rooms: 2,
        bathrooms: 1,
        floor: 9,
        totalFloors: 15,
        buildYear: 2022,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다", "주차가능"],
        description: "합정역 도보 5분, 깔끔한 투룸 오피스텔입니다. 신혼부부 및 2인 가구에 추천합니다.",
        lat: 37.5495,
        lng: 126.9138,
        image: "https://picsum.photos/seed/prop7/400/300",
        agent: {
            name: "윤부동산",
            phone: "010-7890-1234",
            company: "합정부동산"
        },
        premium: false,
        views: 734,
        createdAt: "2025-11-27"
    },
    {
        id: 8,
        title: "망원동 한강뷰 아파트",
        type: "아파트",
        saleType: "매매",
        price: 145000,
        monthlyRent: 0,
        address: "서울시 마포구 망원동 789-12",
        district: "마포구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 18,
        totalFloors: 25,
        buildYear: 2018,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "한강뷰"],
        description: "망원동 한강뷰 아파트입니다. 고층으로 전망이 우수하고 한강공원이 가깝습니다.",
        lat: 37.5564,
        lng: 126.9021,
        image: "https://picsum.photos/seed/prop8/400/300",
        agent: {
            name: "임공인",
            phone: "010-8901-2345",
            company: "망원부동산"
        },
        premium: true,
        views: 2103,
        createdAt: "2025-11-25"
    },

    // 용산구 매물
    {
        id: 9,
        title: "이촌동 한강맨션 리버뷰",
        type: "아파트",
        saleType: "전세",
        price: 55000,
        monthlyRent: 0,
        address: "서울시 용산구 이촌동 345-67",
        district: "용산구",
        area: 95,
        rooms: 3,
        bathrooms: 2,
        floor: 20,
        totalFloors: 30,
        buildYear: 2017,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "한강뷰", "시스템에어컨"],
        description: "이촌동 한강맨션 최상층 리버뷰입니다. 한강조망이 압도적이며 학군이 우수합니다.",
        lat: 37.5219,
        lng: 126.9647,
        image: "https://picsum.photos/seed/prop9/400/300",
        agent: {
            name: "한부동산",
            phone: "010-9012-3456",
            company: "이촌부동산"
        },
        premium: true,
        views: 1678,
        createdAt: "2025-11-26"
    },
    {
        id: 10,
        title: "용산역 초역세권 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 1500,
        monthlyRent: 65,
        address: "서울시 용산구 한강로2가 234-56",
        district: "용산구",
        area: 30,
        rooms: 1,
        bathrooms: 1,
        floor: 11,
        totalFloors: 18,
        buildYear: 2023,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락"],
        description: "용산역 1분 거리 초역세권 오피스텔입니다. 서울역, 숙대입구역 환승 편리합니다.",
        lat: 37.5295,
        lng: 126.9645,
        image: "https://picsum.photos/seed/prop10/400/300",
        agent: {
            name: "송공인중개사",
            phone: "010-0123-4567",
            company: "용산부동산"
        },
        premium: false,
        views: 923,
        createdAt: "2025-11-28"
    },

    // 성동구 매물
    {
        id: 11,
        title: "성수동 대림아크로 신축",
        type: "아파트",
        saleType: "매매",
        price: 132000,
        monthlyRent: 0,
        address: "서울시 성동구 성수동1가 567-89",
        district: "성동구",
        area: 74,
        rooms: 3,
        bathrooms: 2,
        floor: 14,
        totalFloors: 22,
        buildYear: 2023,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨"],
        description: "성수동 핫플레이스 인근 신축 아파트입니다. 대중교통 편리하고 상권 발달했습니다.",
        lat: 37.5447,
        lng: 127.0557,
        image: "https://picsum.photos/seed/prop11/400/300",
        agent: {
            name: "류부동산",
            phone: "010-1234-5670",
            company: "성수부동산"
        },
        premium: true,
        views: 1945,
        createdAt: "2025-11-24"
    },
    {
        id: 12,
        title: "왕십리역 풀옵션 투룸",
        type: "투룸",
        saleType: "월세",
        price: 1000,
        monthlyRent: 75,
        address: "서울시 성동구 왕십리동 123-45",
        district: "성동구",
        area: 40,
        rooms: 2,
        bathrooms: 1,
        floor: 6,
        totalFloors: 10,
        buildYear: 2021,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다"],
        description: "왕십리역 5분 거리 투룸입니다. 풀옵션으로 즉시 입주 가능하며 관리비 저렴합니다.",
        lat: 37.5611,
        lng: 127.0372,
        image: "https://picsum.photos/seed/prop12/400/300",
        agent: {
            name: "신공인",
            phone: "010-2345-6781",
            company: "왕십리부동산"
        },
        premium: false,
        views: 645,
        createdAt: "2025-11-27"
    },

    // 송파구 매물
    {
        id: 13,
        title: "잠실 송파파크하비오",
        type: "아파트",
        saleType: "매매",
        price: 195000,
        monthlyRent: 0,
        address: "서울시 송파구 잠실동 456-78",
        district: "송파구",
        area: 114,
        rooms: 4,
        bathrooms: 3,
        floor: 22,
        totalFloors: 35,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨", "빌트인"],
        description: "잠실 최고급 아파트 송파파크하비오입니다. 롯데월드타워 조망 우수하고 학군 최상위입니다.",
        lat: 37.5134,
        lng: 127.1005,
        image: "https://picsum.photos/seed/prop13/400/300",
        agent: {
            name: "오부동산",
            phone: "010-3456-7892",
            company: "잠실부동산"
        },
        premium: true,
        views: 2876,
        createdAt: "2025-11-23"
    },
    {
        id: 14,
        title: "문정역 신축 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 2000,
        monthlyRent: 60,
        address: "서울시 송파구 문정동 789-12",
        district: "송파구",
        area: 33,
        rooms: 1,
        bathrooms: 1,
        floor: 10,
        totalFloors: 16,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락", "택배보관함"],
        description: "문정역 도보 3분 신축 오피스텔입니다. 가든파이브 인근으로 쇼핑 편리합니다.",
        lat: 37.4845,
        lng: 127.1226,
        image: "https://picsum.photos/seed/prop14/400/300",
        agent: {
            name: "하공인중개사",
            phone: "010-4567-8903",
            company: "문정부동산"
        },
        premium: true,
        views: 1234,
        createdAt: "2025-11-28"
    },
    {
        id: 15,
        title: "가락시장역 투룸 오피스텔",
        type: "투룸",
        saleType: "전세",
        price: 28000,
        monthlyRent: 0,
        address: "서울시 송파구 가락동 234-56",
        district: "송파구",
        area: 48,
        rooms: 2,
        bathrooms: 1,
        floor: 8,
        totalFloors: 14,
        buildYear: 2022,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다", "주차가능"],
        description: "가락시장역 도보 5분 투룸 오피스텔입니다. 넓은 평수로 2인 가구에 적합합니다.",
        lat: 37.4921,
        lng: 127.1182,
        image: "https://picsum.photos/seed/prop15/400/300",
        agent: {
            name: "고부동산",
            phone: "010-5678-9014",
            company: "가락부동산"
        },
        premium: false,
        views: 789,
        createdAt: "2025-11-26"
    },

    // 추가 매물 (강남구)
    {
        id: 16,
        title: "역삼동 테헤란로 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 3000,
        monthlyRent: 75,
        address: "서울시 강남구 역삼동 567-89",
        district: "강남구",
        area: 36,
        rooms: 1,
        bathrooms: 1,
        floor: 15,
        totalFloors: 20,
        buildYear: 2023,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락", "주차가능"],
        description: "테헤란로 대로변 오피스텔입니다. IT 기업 밀집 지역으로 직장인에게 최적입니다.",
        lat: 37.5003,
        lng: 127.0362,
        image: "https://picsum.photos/seed/prop16/400/300",
        agent: {
            name: "장공인",
            phone: "010-6789-0125",
            company: "역삼부동산"
        },
        premium: true,
        views: 1567,
        createdAt: "2025-11-27"
    },
    {
        id: 17,
        title: "대치동 은마아파트",
        type: "아파트",
        saleType: "매매",
        price: 225000,
        monthlyRent: 0,
        address: "서울시 강남구 대치동 123-45",
        district: "강남구",
        area: 134,
        rooms: 4,
        bathrooms: 3,
        floor: 12,
        totalFloors: 15,
        buildYear: 2015,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨"],
        description: "대치동 은마아파트 134㎡입니다. 대치동 학군 최상위이며 재건축 대기 중입니다.",
        lat: 37.4947,
        lng: 127.0626,
        image: "https://picsum.photos/seed/prop17/400/300",
        agent: {
            name: "조부동산",
            phone: "010-7890-1236",
            company: "대치부동산"
        },
        premium: true,
        views: 3421,
        createdAt: "2025-11-22"
    },

    // 추가 매물 (서초구)
    {
        id: 18,
        title: "반포동 아크로리버파크",
        type: "아파트",
        saleType: "전세",
        price: 85000,
        monthlyRent: 0,
        address: "서울시 서초구 반포동 456-78",
        district: "서초구",
        area: 124,
        rooms: 4,
        bathrooms: 2,
        floor: 25,
        totalFloors: 32,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "한강뷰", "시스템에어컨", "빌트인"],
        description: "반포동 아크로리버파크 한강뷰 최상급 아파트입니다. 초중고 도보권이며 한강공원 바로 앞입니다.",
        lat: 37.5074,
        lng: 126.9967,
        image: "https://picsum.photos/seed/prop18/400/300",
        agent: {
            name: "차공인중개사",
            phone: "010-8901-2347",
            company: "반포부동산"
        },
        premium: true,
        views: 2654,
        createdAt: "2025-11-24"
    },
    {
        id: 19,
        title: "서초역 풀옵션 원룸",
        type: "원룸",
        saleType: "월세",
        price: 1500,
        monthlyRent: 60,
        address: "서울시 서초구 서초동 789-12",
        district: "서초구",
        area: 28,
        rooms: 1,
        bathrooms: 1,
        floor: 7,
        totalFloors: 12,
        buildYear: 2022,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장"],
        description: "서초역 도보 2분 풀옵션 원룸입니다. 관리비 저렴하고 치안 우수한 지역입니다.",
        lat: 37.4837,
        lng: 127.0102,
        image: "https://picsum.photos/seed/prop19/400/300",
        agent: {
            name: "추부동산",
            phone: "010-9012-3458",
            company: "서초부동산"
        },
        premium: false,
        views: 834,
        createdAt: "2025-11-28"
    },

    // 추가 매물 (마포구)
    {
        id: 20,
        title: "상암DMC 래미안",
        type: "아파트",
        saleType: "매매",
        price: 158000,
        monthlyRent: 0,
        address: "서울시 마포구 상암동 234-56",
        district: "마포구",
        area: 98,
        rooms: 3,
        bathrooms: 2,
        floor: 18,
        totalFloors: 28,
        buildYear: 2019,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨"],
        description: "상암DMC 래미안 아파트입니다. 디지털미디어시티역 5분, 학군 우수합니다.",
        lat: 37.5794,
        lng: 126.8895,
        image: "https://picsum.photos/seed/prop20/400/300",
        agent: {
            name: "편공인",
            phone: "010-0123-4578",
            company: "상암부동산"
        },
        premium: true,
        views: 1987,
        createdAt: "2025-11-25"
    },

    // 강남구 추가
    {
        id: 21,
        title: "삼성역 코엑스 인근 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 4000,
        monthlyRent: 80,
        address: "서울시 강남구 삼성동 567-12",
        district: "강남구",
        area: 38,
        rooms: 1,
        bathrooms: 1,
        floor: 20,
        totalFloors: 25,
        buildYear: 2023,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락", "주차가능", "피트니스"],
        description: "삼성역 5분, 코엑스 인근 프리미엄 오피스텔입니다. 최신 시설과 편의성이 뛰어납니다.",
        lat: 37.5087,
        lng: 127.0633,
        image: "https://picsum.photos/seed/prop21/400/300",
        agent: {
            name: "표부동산",
            phone: "010-1234-5689",
            company: "삼성부동산"
        },
        premium: true,
        views: 1876,
        createdAt: "2025-11-27"
    },
    {
        id: 22,
        title: "개포동 개포주공 재건축",
        type: "아파트",
        saleType: "매매",
        price: 125000,
        monthlyRent: 0,
        address: "서울시 강남구 개포동 123-89",
        district: "강남구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 8,
        totalFloors: 15,
        buildYear: 1985,
        options: ["냉장고", "세탁기", "가스레인지", "붙박이장", "주차가능"],
        description: "개포동 주공아파트 재건축 예정입니다. 84㎡ 구조이며 투자가치가 높습니다.",
        lat: 37.4861,
        lng: 127.0626,
        image: "https://picsum.photos/seed/prop22/400/300",
        agent: {
            name: "한부동산",
            phone: "010-2345-6790",
            company: "개포부동산"
        },
        premium: false,
        views: 2341,
        createdAt: "2025-11-26"
    },
    {
        id: 23,
        title: "도곡동 타워팰리스",
        type: "아파트",
        saleType: "매매",
        price: 385000,
        monthlyRent: 0,
        address: "서울시 강남구 도곡동 456-23",
        district: "강남구",
        area: 244,
        rooms: 5,
        bathrooms: 4,
        floor: 45,
        totalFloors: 73,
        buildYear: 2002,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨", "빌트인", "컨시어지"],
        description: "타워팰리스 244㎡ 펜트하우스급 매물입니다. 강남 최고급 주거공간으로 전망이 압도적입니다.",
        lat: 37.4891,
        lng: 127.0541,
        image: "https://picsum.photos/seed/prop23/400/300",
        agent: {
            name: "허공인중개사",
            phone: "010-3456-7801",
            company: "도곡부동산"
        },
        premium: true,
        views: 5432,
        createdAt: "2025-11-21"
    },

    // 서초구 추가
    {
        id: 24,
        title: "양재역 신축 투룸",
        type: "투룸",
        saleType: "월세",
        price: 3000,
        monthlyRent: 85,
        address: "서울시 서초구 양재동 234-67",
        district: "서초구",
        area: 45,
        rooms: 2,
        bathrooms: 1,
        floor: 11,
        totalFloors: 15,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다", "주차가능"],
        description: "양재역 초역세권 신축 투룸입니다. 신분당선 환승으로 판교까지 빠른 접근 가능합니다.",
        lat: 37.4842,
        lng: 127.0344,
        image: "https://picsum.photos/seed/prop24/400/300",
        agent: {
            name: "홍부동산",
            phone: "010-4567-8012",
            company: "양재부동산"
        },
        premium: true,
        views: 1234,
        createdAt: "2025-11-28"
    },
    {
        id: 25,
        title: "내곡동 힐스테이트",
        type: "아파트",
        saleType: "전세",
        price: 48000,
        monthlyRent: 0,
        address: "서울시 서초구 내곡동 567-45",
        district: "서초구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 15,
        totalFloors: 20,
        buildYear: 2021,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장"],
        description: "내곡동 힐스테이트 신축 아파트입니다. 조용한 주거환경과 우수한 학군을 자랑합니다.",
        lat: 37.4620,
        lng: 127.0825,
        image: "https://picsum.photos/seed/prop25/400/300",
        agent: {
            name: "황공인",
            phone: "010-5678-9023",
            company: "내곡부동산"
        },
        premium: false,
        views: 987,
        createdAt: "2025-11-27"
    },

    // 용산구 추가
    {
        id: 26,
        title: "한남동 나인원 한남",
        type: "아파트",
        saleType: "매매",
        price: 420000,
        monthlyRent: 0,
        address: "서울시 용산구 한남동 789-34",
        district: "용산구",
        area: 244,
        rooms: 4,
        bathrooms: 4,
        floor: 35,
        totalFloors: 49,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "한강뷰", "시스템에어컨", "빌트인", "컨시어지"],
        description: "한남동 나인원 한남 최상급 아파트입니다. 한강조망과 남산뷰가 환상적이며 최고급 시설을 갖추고 있습니다.",
        lat: 37.5342,
        lng: 127.0021,
        image: "https://picsum.photos/seed/prop26/400/300",
        agent: {
            name: "감공인중개사",
            phone: "010-6789-0134",
            company: "한남부동산"
        },
        premium: true,
        views: 6789,
        createdAt: "2025-11-20"
    },
    {
        id: 27,
        title: "용산 아이파크몰 인근 오피스텔",
        type: "원룸",
        saleType: "월세",
        price: 2000,
        monthlyRent: 70,
        address: "서울시 용산구 한강로3가 234-56",
        district: "용산구",
        area: 32,
        rooms: 1,
        bathrooms: 1,
        floor: 16,
        totalFloors: 22,
        buildYear: 2023,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락"],
        description: "용산 아이파크몰 도보 5분 거리입니다. 쇼핑과 문화생활이 편리한 위치입니다.",
        lat: 37.5265,
        lng: 126.9656,
        image: "https://picsum.photos/seed/prop27/400/300",
        agent: {
            name: "남부동산",
            phone: "010-7890-1245",
            company: "용산중앙부동산"
        },
        premium: true,
        views: 1456,
        createdAt: "2025-11-27"
    },

    // 성동구 추가
    {
        id: 28,
        title: "성수동 갤러리아포레",
        type: "아파트",
        saleType: "매매",
        price: 168000,
        monthlyRent: 0,
        address: "서울시 성동구 성수동2가 345-78",
        district: "성동구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 20,
        totalFloors: 35,
        buildYear: 2021,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨"],
        description: "성수동 갤러리아포레 신축 아파트입니다. 한강조망과 성수동 핫플레이스 인근입니다.",
        lat: 37.5423,
        lng: 127.0556,
        image: "https://picsum.photos/seed/prop28/400/300",
        agent: {
            name: "도공인",
            phone: "010-8901-2356",
            company: "성수중앙부동산"
        },
        premium: true,
        views: 2345,
        createdAt: "2025-11-25"
    },
    {
        id: 29,
        title: "뚝섬역 풀옵션 원룸",
        type: "원룸",
        saleType: "월세",
        price: 1000,
        monthlyRent: 58,
        address: "서울시 성동구 성수동1가 123-67",
        district: "성동구",
        area: 26,
        rooms: 1,
        bathrooms: 1,
        floor: 5,
        totalFloors: 8,
        buildYear: 2022,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장"],
        description: "뚝섬역 5분 거리 풀옵션 원룸입니다. 한강공원이 가까워 산책하기 좋습니다.",
        lat: 37.5467,
        lng: 127.0471,
        image: "https://picsum.photos/seed/prop29/400/300",
        agent: {
            name: "문부동산",
            phone: "010-9012-3467",
            company: "뚝섬부동산"
        },
        premium: false,
        views: 723,
        createdAt: "2025-11-28"
    },

    // 송파구 추가
    {
        id: 30,
        title: "잠실 엘스",
        type: "아파트",
        saleType: "전세",
        price: 95000,
        monthlyRent: 0,
        address: "서울시 송파구 잠실동 678-45",
        district: "송파구",
        area: 144,
        rooms: 4,
        bathrooms: 3,
        floor: 28,
        totalFloors: 45,
        buildYear: 2017,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨", "빌트인"],
        description: "잠실 엘스 144㎡ 고급 아파트입니다. 롯데월드타워뷰와 최상급 학군을 자랑합니다.",
        lat: 37.5147,
        lng: 127.1023,
        image: "https://picsum.photos/seed/prop30/400/300",
        agent: {
            name: "박공인중개사",
            phone: "010-0123-4589",
            company: "잠실중앙부동산"
        },
        premium: true,
        views: 3214,
        createdAt: "2025-11-24"
    },
    {
        id: 31,
        title: "송파역 신축 투룸",
        type: "투룸",
        saleType: "월세",
        price: 2500,
        monthlyRent: 75,
        address: "서울시 송파구 송파동 234-89",
        district: "송파구",
        area: 44,
        rooms: 2,
        bathrooms: 1,
        floor: 12,
        totalFloors: 18,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다", "주차가능"],
        description: "송파역 도보 3분 신축 투룸입니다. 분리형 구조로 신혼부부에게 적합합니다.",
        lat: 37.5045,
        lng: 127.1110,
        image: "https://picsum.photos/seed/prop31/400/300",
        agent: {
            name: "서부동산",
            phone: "010-1234-5690",
            company: "송파부동산"
        },
        premium: true,
        views: 1123,
        createdAt: "2025-11-28"
    },
    {
        id: 32,
        title: "석촌호수 롯데캐슬골드",
        type: "아파트",
        saleType: "매매",
        price: 175000,
        monthlyRent: 0,
        address: "서울시 송파구 석촌동 567-23",
        district: "송파구",
        area: 104,
        rooms: 4,
        bathrooms: 2,
        floor: 22,
        totalFloors: 30,
        buildYear: 2019,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨"],
        description: "석촌호수 롯데캐슬골드 아파트입니다. 석촌호수뷰와 롯데월드 인근으로 생활편의성이 뛰어납니다.",
        lat: 37.5067,
        lng: 127.0976,
        image: "https://picsum.photos/seed/prop32/400/300",
        agent: {
            name: "안공인",
            phone: "010-2345-6701",
            company: "석촌부동산"
        },
        premium: true,
        views: 2567,
        createdAt: "2025-11-26"
    },

    // 마포구 추가
    {
        id: 33,
        title: "공덕역 마포래미안푸르지오",
        type: "아파트",
        saleType: "전세",
        price: 58000,
        monthlyRent: 0,
        address: "서울시 마포구 공덕동 123-78",
        district: "마포구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 16,
        totalFloors: 25,
        buildYear: 2018,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장"],
        description: "공덕역 5분 거리 마포래미안푸르지오입니다. 직장인에게 최적화된 교통환경입니다.",
        lat: 37.5443,
        lng: 126.9512,
        image: "https://picsum.photos/seed/prop33/400/300",
        agent: {
            name: "유부동산",
            phone: "010-3456-7012",
            company: "공덕부동산"
        },
        premium: false,
        views: 1678,
        createdAt: "2025-11-27"
    },
    {
        id: 34,
        title: "신촌역 풀옵션 원룸",
        type: "원룸",
        saleType: "월세",
        price: 500,
        monthlyRent: 55,
        address: "서울시 마포구 신촌동 456-34",
        district: "마포구",
        area: 24,
        rooms: 1,
        bathrooms: 1,
        floor: 4,
        totalFloors: 7,
        buildYear: 2021,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장"],
        description: "신촌역 도보 5분 풀옵션 원룸입니다. 대학가 인근으로 학생 및 직장인에게 적합합니다.",
        lat: 37.5556,
        lng: 126.9369,
        image: "https://picsum.photos/seed/prop34/400/300",
        agent: {
            name: "윤공인중개사",
            phone: "010-4567-8123",
            company: "신촌부동산"
        },
        premium: false,
        views: 892,
        createdAt: "2025-11-28"
    },
    {
        id: 35,
        title: "연남동 빌라",
        type: "투룸",
        saleType: "월세",
        price: 2000,
        monthlyRent: 70,
        address: "서울시 마포구 연남동 234-67",
        district: "마포구",
        area: 42,
        rooms: 2,
        bathrooms: 1,
        floor: 2,
        totalFloors: 3,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다"],
        description: "연남동 핫플레이스 중심의 깔끔한 빌라입니다. 카페와 맛집이 즐비한 지역입니다.",
        lat: 37.5656,
        lng: 126.9241,
        image: "https://picsum.photos/seed/prop35/400/300",
        agent: {
            name: "이부동산",
            phone: "010-5678-9234",
            company: "연남부동산"
        },
        premium: true,
        views: 1234,
        createdAt: "2025-11-27"
    },

    // 추가 프리미엄 매물들
    {
        id: 36,
        title: "청담동 신축 럭셔리 빌라",
        type: "빌라",
        saleType: "매매",
        price: 285000,
        monthlyRent: 0,
        address: "서울시 강남구 청담동 123-45",
        district: "강남구",
        area: 165,
        rooms: 4,
        bathrooms: 3,
        floor: 3,
        totalFloors: 4,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "시스템에어컨", "빌트인", "엘리베이터"],
        description: "청담동 신축 럭셔리 단독주택형 빌라입니다. 프라이빗한 공간과 최고급 마감재로 시공되었습니다.",
        lat: 37.5229,
        lng: 127.0474,
        image: "https://picsum.photos/seed/prop36/400/300",
        agent: {
            name: "전공인중개사",
            phone: "010-6789-0345",
            company: "청담부동산"
        },
        premium: true,
        views: 4567,
        createdAt: "2025-11-23"
    },
    {
        id: 37,
        title: "방이역 올림픽선수촌아파트",
        type: "아파트",
        saleType: "전세",
        price: 42000,
        monthlyRent: 0,
        address: "서울시 송파구 방이동 678-90",
        district: "송파구",
        area: 74,
        rooms: 3,
        bathrooms: 2,
        floor: 9,
        totalFloors: 15,
        buildYear: 1988,
        options: ["냉장고", "세탁기", "가스레인지", "붙박이장", "주차가능"],
        description: "방이역 올림픽공원 인근 선수촌아파트입니다. 재건축 기대감이 높은 지역입니다.",
        lat: 37.5109,
        lng: 127.1260,
        image: "https://picsum.photos/seed/prop37/400/300",
        agent: {
            name: "최부동산",
            phone: "010-7890-1456",
            company: "방이부동산"
        },
        premium: false,
        views: 1567,
        createdAt: "2025-11-26"
    },
    {
        id: 38,
        title: "여의도 트럼프월드",
        type: "아파트",
        saleType: "매매",
        price: 245000,
        monthlyRent: 0,
        address: "서울시 영등포구 여의도동 23-1",
        district: "영등포구",
        area: 114,
        rooms: 3,
        bathrooms: 2,
        floor: 35,
        totalFloors: 47,
        buildYear: 2002,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "베란다확장", "한강뷰", "시스템에어컨"],
        description: "여의도 트럼프월드 한강조망 최상급 아파트입니다. 63빌딩과 국회의사당이 한눈에 보입니다.",
        lat: 37.5219,
        lng: 126.9267,
        image: "https://picsum.photos/seed/prop38/400/300",
        agent: {
            name: "강부동산",
            phone: "010-8901-2567",
            company: "여의도부동산"
        },
        premium: true,
        views: 3892,
        createdAt: "2025-11-22"
    },
    {
        id: 39,
        title: "건대입구역 스타시티",
        type: "원룸",
        saleType: "월세",
        price: 1000,
        monthlyRent: 62,
        address: "서울시 광진구 화양동 234-56",
        district: "광진구",
        area: 30,
        rooms: 1,
        bathrooms: 1,
        floor: 14,
        totalFloors: 20,
        buildYear: 2023,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락"],
        description: "건대입구역 초역세권 스타시티 오피스텔입니다. 대학생 및 신입사원에게 최적입니다.",
        lat: 37.5404,
        lng: 127.0697,
        image: "https://picsum.photos/seed/prop39/400/300",
        agent: {
            name: "노공인",
            phone: "010-9012-3678",
            company: "건대부동산"
        },
        premium: false,
        views: 1098,
        createdAt: "2025-11-28"
    },
    {
        id: 40,
        title: "목동 신시가지 아파트",
        type: "아파트",
        saleType: "전세",
        price: 52000,
        monthlyRent: 0,
        address: "서울시 양천구 목동 567-123",
        district: "양천구",
        area: 104,
        rooms: 4,
        bathrooms: 2,
        floor: 12,
        totalFloors: 20,
        buildYear: 2016,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장"],
        description: "목동 신시가지 아파트입니다. 학군이 뛰어나고 주변 생활 인프라가 잘 갖춰져 있습니다.",
        lat: 37.5264,
        lng: 126.8756,
        image: "https://picsum.photos/seed/prop40/400/300",
        agent: {
            name: "민부동산",
            phone: "010-0123-4789",
            company: "목동부동산"
        },
        premium: false,
        views: 1345,
        createdAt: "2025-11-27"
    },
    {
        id: 41,
        title: "광화문 더 케이트윈타워",
        type: "오피스텔",
        saleType: "월세",
        price: 5000,
        monthlyRent: 90,
        address: "서울시 종로구 세종로 123-45",
        district: "종로구",
        area: 40,
        rooms: 1,
        bathrooms: 1,
        floor: 28,
        totalFloors: 40,
        buildYear: 2022,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락", "주차가능", "피트니스", "컨시어지"],
        description: "광화문 더 케이트윈타워 프리미엄 오피스텔입니다. 도심 최고의 입지와 뷰를 자랑합니다.",
        lat: 37.5720,
        lng: 126.9765,
        image: "https://picsum.photos/seed/prop41/400/300",
        agent: {
            name: "배공인중개사",
            phone: "010-1234-6890",
            company: "광화문부동산"
        },
        premium: true,
        views: 2789,
        createdAt: "2025-11-26"
    },
    {
        id: 42,
        title: "서울대입구역 관악 푸르지오",
        type: "아파트",
        saleType: "전세",
        price: 38000,
        monthlyRent: 0,
        address: "서울시 관악구 봉천동 234-67",
        district: "관악구",
        area: 74,
        rooms: 3,
        bathrooms: 2,
        floor: 10,
        totalFloors: 18,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장"],
        description: "서울대입구역 도보 5분 관악 푸르지오입니다. 서울대 인근으로 교육환경이 우수합니다.",
        lat: 37.4812,
        lng: 126.9525,
        image: "https://picsum.photos/seed/prop42/400/300",
        agent: {
            name: "사부동산",
            phone: "010-2345-7901",
            company: "관악부동산"
        },
        premium: false,
        views: 1123,
        createdAt: "2025-11-27"
    },
    {
        id: 43,
        title: "성북동 단독주택",
        type: "단독주택",
        saleType: "매매",
        price: 195000,
        monthlyRent: 0,
        address: "서울시 성북구 성북동 456-89",
        district: "성북구",
        area: 198,
        rooms: 5,
        bathrooms: 3,
        floor: 2,
        totalFloors: 2,
        buildYear: 2019,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "드레스룸", "주차가능", "마당", "테라스"],
        description: "성북동 한옥마을 인근 현대식 단독주택입니다. 넓은 마당과 테라스가 있어 여유로운 생활이 가능합니다.",
        lat: 37.5891,
        lng: 127.0089,
        image: "https://picsum.photos/seed/prop43/400/300",
        agent: {
            name: "아공인",
            phone: "010-3456-8012",
            company: "성북부동산"
        },
        premium: true,
        views: 2456,
        createdAt: "2025-11-24"
    },
    {
        id: 44,
        title: "노원역 상계주공아파트",
        type: "아파트",
        saleType: "전세",
        price: 28000,
        monthlyRent: 0,
        address: "서울시 노원구 상계동 678-12",
        district: "노원구",
        area: 59,
        rooms: 3,
        bathrooms: 1,
        floor: 7,
        totalFloors: 15,
        buildYear: 1990,
        options: ["냉장고", "세탁기", "가스레인지", "붙박이장", "주차가능"],
        description: "노원역 상계주공아파트입니다. 교통 편리하고 주변 생활 인프라가 잘 갖춰져 있습니다.",
        lat: 37.6553,
        lng: 127.0623,
        image: "https://picsum.photos/seed/prop44/400/300",
        agent: {
            name: "자부동산",
            phone: "010-4567-9123",
            company: "노원부동산"
        },
        premium: false,
        views: 834,
        createdAt: "2025-11-28"
    },
    {
        id: 45,
        title: "신도림역 테크노마트",
        type: "오피스텔",
        saleType: "월세",
        price: 1500,
        monthlyRent: 65,
        address: "서울시 구로구 구로동 123-45",
        district: "구로구",
        area: 33,
        rooms: 1,
        bathrooms: 1,
        floor: 18,
        totalFloors: 30,
        buildYear: 2021,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장", "붙박이장", "전자도어락"],
        description: "신도림역 테크노마트 오피스텔입니다. 쇼핑몰과 연결되어 생활 편의성이 뛰어납니다.",
        lat: 37.5084,
        lng: 126.8911,
        image: "https://picsum.photos/seed/prop45/400/300",
        agent: {
            name: "차공인",
            phone: "010-5678-0234",
            company: "구로부동산"
        },
        premium: false,
        views: 967,
        createdAt: "2025-11-28"
    },
    {
        id: 46,
        title: "천호동 올림픽파크포레온",
        type: "아파트",
        saleType: "매매",
        price: 112000,
        monthlyRent: 0,
        address: "서울시 강동구 천호동 456-78",
        district: "강동구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 15,
        totalFloors: 25,
        buildYear: 2018,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장"],
        description: "천호동 올림픽파크포레온 아파트입니다. 올림픽공원이 가까워 쾌적한 주거환경을 제공합니다.",
        lat: 37.5384,
        lng: 127.1238,
        image: "https://picsum.photos/seed/prop46/400/300",
        agent: {
            name: "카부동산",
            phone: "010-6789-1345",
            company: "천호부동산"
        },
        premium: false,
        views: 1567,
        createdAt: "2025-11-26"
    },
    {
        id: 47,
        title: "답십리역 신축 투룸",
        type: "투룸",
        saleType: "월세",
        price: 2000,
        monthlyRent: 68,
        address: "서울시 동대문구 답십리동 234-56",
        district: "동대문구",
        area: 43,
        rooms: 2,
        bathrooms: 1,
        floor: 9,
        totalFloors: 14,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다"],
        description: "답십리역 초역세권 신축 투룸입니다. 분리형 구조로 신혼부부에게 적합합니다.",
        lat: 37.5663,
        lng: 127.0563,
        image: "https://picsum.photos/seed/prop47/400/300",
        agent: {
            name: "타공인중개사",
            phone: "010-7890-2456",
            company: "답십리부동산"
        },
        premium: true,
        views: 1089,
        createdAt: "2025-11-28"
    },
    {
        id: 48,
        title: "혜화역 대학로 원룸",
        type: "원룸",
        saleType: "월세",
        price: 500,
        monthlyRent: 52,
        address: "서울시 종로구 혜화동 123-45",
        district: "종로구",
        area: 22,
        rooms: 1,
        bathrooms: 1,
        floor: 3,
        totalFloors: 5,
        buildYear: 2020,
        options: ["에어컨", "냉장고", "세탁기", "인덕션", "신발장"],
        description: "혜화역 대학로 원룸입니다. 문화생활이 풍부하고 대학가 인근으로 활기찬 분위기입니다.",
        lat: 37.5821,
        lng: 127.0012,
        image: "https://picsum.photos/seed/prop48/400/300",
        agent: {
            name: "파부동산",
            phone: "010-8901-3567",
            company: "혜화부동산"
        },
        premium: false,
        views: 756,
        createdAt: "2025-11-28"
    },
    {
        id: 49,
        title: "금호동 옥수 하이츠",
        type: "아파트",
        saleType: "전세",
        price: 45000,
        monthlyRent: 0,
        address: "서울시 성동구 금호동 567-89",
        district: "성동구",
        area: 84,
        rooms: 3,
        bathrooms: 2,
        floor: 18,
        totalFloors: 25,
        buildYear: 2016,
        options: ["에어컨", "냉장고", "세탁기", "식기세척기", "붙박이장", "신발장", "드레스룸", "주차가능", "베란다확장", "한강뷰"],
        description: "금호동 옥수 하이츠 한강뷰 아파트입니다. 한강조망이 우수하고 교통이 편리합니다.",
        lat: 37.5404,
        lng: 127.0179,
        image: "https://picsum.photos/seed/prop49/400/300",
        agent: {
            name: "하부동산",
            phone: "010-9012-4678",
            company: "금호부동산"
        },
        premium: false,
        views: 1456,
        createdAt: "2025-11-27"
    },
    {
        id: 50,
        title: "성수동 카페거리 신축빌라",
        type: "빌라",
        saleType: "월세",
        price: 3000,
        monthlyRent: 85,
        address: "서울시 성동구 성수동2가 123-56",
        district: "성동구",
        area: 52,
        rooms: 2,
        bathrooms: 1,
        floor: 3,
        totalFloors: 4,
        buildYear: 2024,
        options: ["에어컨", "냉장고", "세탁기", "가스레인지", "신발장", "붙박이장", "베란다", "테라스"],
        description: "성수동 카페거리 중심의 신축 빌라입니다. 루프탑 테라스가 있어 여유로운 생활이 가능합니다.",
        lat: 37.5445,
        lng: 127.0551,
        image: "https://picsum.photos/seed/prop50/400/300",
        agent: {
            name: "거공인",
            phone: "010-0123-5789",
            company: "성수카페부동산"
        },
        premium: true,
        views: 1987,
        createdAt: "2025-11-27"
    }
];

// 필터링 및 검색을 위한 상수
const DISTRICTS = ['전체', '강남구', '서초구', '마포구', '용산구', '성동구', '송파구', '영등포구', '광진구', '양천구', '종로구', '관악구', '성북구', '노원구', '구로구', '강동구', '동대문구'];
const SALE_TYPES = ['전체', '월세', '전세', '매매'];
const PROPERTY_TYPES = ['전체', '원룸', '투룸', '아파트', '오피스텔', '빌라', '단독주택'];
const PRICE_RANGES = {
    '월세': ['전체', '50만원 이하', '50-70만원', '70-90만원', '90만원 이상'],
    '전세': ['전체', '3억 이하', '3-5억', '5-7억', '7억 이상'],
    '매매': ['전체', '10억 이하', '10-15억', '15-20억', '20억 이상']
};
